### ISSUE TITLE
Are very long ri documentation build times expected?

### ISSUE THREAD

**Issue by oddhack** [gjtorikian/mathematical#104]
When I update mathematical to 1.6.14 with 'gem update', it takes about 15 minutes on a Ryzen 2600 for the 'Installing ri documentation for mathematical' step to complete, compared to seconds for every other package. Is this normal behavior?

**Comment by gjtorikian** [comment]
I'm not at all sure what `ri` is. Would you be able to post a complete log?

**Comment by oddhack** [comment]
Hm, now I can't reproduce this. I had done a 'gem update' to update all gems and it got hung up at the specified step (which is, to my vague understanding, some sort of automatically generated API documentation for the gem). Attempts to reproduce that behavior by entirely backing out mathematical then installing 1.6.13 and updating to 1.6.14 did not suffer this behavior, though, so perhaps I misunderstood why gem update was hanging up. Sorry for the false alarm and if I can reproduce it, will let you know.
