### ISSUE TITLE
No gem for 1.6.16

### ISSUE THREAD

**Issue by rpsene** [gjtorikian/mathematical#117]
[The lack of gem for the version 1.6.16](https://index.rubygems.org/gems/mathematical) is breaking builds:

`gem update --system; gem install asciidoctor-mathematical          1054.8s
 => => # installed?'
 => => # from /usr/lib/ruby/vendor_ruby/rubygems/request_set.rb:173:in `block (2 levels)
 => => #  in install'
 => => # ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
 => => #     bad response Forbidden 403 (https://index.rubygems.org/quick/Marshal.4.8/ma
 => => # thematical-1.6.16.gemspec.rz)`
 
 To overcome this problem we had to set mathematical:1.6.14

**Comment by rpsene** [comment]
Issue in asciidoctor-mathematical: https://github.com/asciidoctor/asciidoctor-mathematical/issues/122

**Comment by bwklein** [comment]
It was yanked - https://rubygems.org/gems/mathematical/versions/1.6.16

**Comment by 4e554c4c** [comment]
should be fixed in `v1.6.18`
