### ISSUE TITLE
script/bootstrap requires sudo

### ISSUE THREAD

**Issue by gl-yziquel** [gjtorikian/mathematical#129]
It just so happens that, on my machine, which is ubuntu with ruby installed from ubuntu (if I remember well), execution of the `script/bootstrap` script requires using `sudo`. Which I heavily dislike.

Could it be possible to avoid running sudo with that script ?

**Comment by 4e554c4c** [comment]
No. The purpose of this script is to install packages, which inherently requires administrator access. If you would not like to run the script, you can install the packages yourself.

**Comment by gl-yziquel** [comment]
`set -x BUNDLE_PATH (ruby -e 'puts Gem.user_dir')`

That solved it for the `fish` shell.

It still asks for sudo, but for `apt-get`.
