### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by 4e554c4c** [gjtorikian/mathematical#139]
The release workflow appears to be broken. I tried to cut a release in #137 and #138 to no avail.

Either the workflow here or in https://github.com/yettoapp/actions is broken, so we need to fix that or have @gjtorikian push a release manually.

**Comment by gjtorikian** [comment]
Yes, the workflow file was wrong. I modernized it and 1.6.20 is out now.

**Comment by cmuellner** [comment]
Thank you very much!
