### ISSUE TITLE
Can't load the library, silent problem with the building?

### ISSUE THREAD

**Issue by Dalar** [gjtorikian/mathematical#58]
Hello,

I followed OS X instructions, but I can't get the library to load. The same issue happens even if I build the gem myself, following instructions. No errors there, just some warnings. I also tried to built `mtex2MML` separately and the tests there ran fine.

```
$ ruby test/test_helper.rb
/Users/amodig/Dev/mathematical/lib/mathematical.rb:1:in `require': incompatible library version - /Users/amodig/Dev/mathematical/lib/mathematical/mathematical.bundle (fatal)
	from /Users/amodig/Dev/mathematical/lib/mathematical.rb:1:in `<top (required)>'
	from test/test_helper.rb:2:in `require'
	from test/test_helper.rb:2:in `<main>'
```

I've installed Ruby through `rbenv` (which is installed through `brew`).
```
 $ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin13]
```

I don't know Ruby so I'm pretty much clueless here. Working on OSX 10.9.5 Mavericks.

**Comment by gjtorikian** [comment]
` incompatible library version` almost certainly means that the gem was built with a Ruby version different than the one you're running. Could you try:

```
rbenv rehash
git clean -fd
```

And trying to build locally once more?

**Comment by Dalar** [comment]
Got back to this... Sorry, no help. I started from a fresh repo.

**Comment by gjtorikian** [comment]
FWIW I'm getting this too. Do you use `rbenv` out of curiosity?

**Comment by Dalar** [comment]
Yes, I did.
