### ISSUE TITLE
Incompatibility with `ruby-enum` v0.7.1

### ISSUE THREAD

**Issue by lmshk** [gjtorikian/mathematical#69]
I cannot `require 'mathematical'` when using ruby-enum v0.7.1; the error is:

    NameError: wrong constant name default
    from <path/to/gem>/lib/ruby-enum/enum.rb:34:in `const_set'

(This also prevents me from using asciidoctor-mathematical.)

*Downgrading ruby-enum to v0.7.0 works.*

**Comment by gjtorikian** [comment]
I'm looking into it, thanks for the report!

**Comment by oddhack** [comment]
Same problem, downgrading to 0.7.0 also appears to work for me.
