### ISSUE TITLE
Unable to load gem

### ISSUE THREAD

**Issue by xsrvmy** [gjtorikian/mathematical#76]
I recently installed this gem, and the `require 'mathematical'` command fails to work with a file not found error. I tried uninstalling and reinstalling but that does not help. Even more confusing: the .so file actually exists but ruby cannot find it.

**Comment by gjtorikian** [comment]
What's your Ruby version? What's the gem version? What's your operating system? Do you have these dependencies: https://github.com/gjtorikian/mathematical#building

**Comment by xsrvmy** [comment]
I am using ruby 2.3.1 and mathematical 1.6.9 ob ubuntu 16.04. I checked and the error and it was actually a file not found error for liblasem.so

**Comment by gjtorikian** [comment]
Do you have all those dependencies I mentioned?

A missing `liblasem.so` implies that the C program that mostly powers Mathematical could not be found. One reason that might be true is that the program did not compile at all.

**Comment by 4e554c4c** [comment]
needs reproduction steps
