### ISSUE TITLE
Generated images seem buggy

### ISSUE THREAD

**Issue by lschmelzeisen** [gjtorikian/mathematical#79]
Currently, the images generated by mathematical seem buggy.

For instance, the following programm

```ruby
require 'mathematical'

options = {format: :png, ppi: 300.0}
renderer = Mathematical.new options
result = renderer.render '$\begin{array}{c} {x = \frac{{ - b \pm \sqrt {b^2 - 4ac} }}{{2a}}} & when & {ax^2 + bx + c = 0} \end{array}$'
::IO.write 'test.png', result[:data]
```

generates the output

![test](https://user-images.githubusercontent.com/488697/30799432-1d468d60-a1dd-11e7-8db1-a6552d8c66c6.png)

which clearly has an incorrect square root. The LaTeX expression is from the mathematical homepage, so I guess it should work.

I used ruby version `2.4.2` and mathematical `1.6.11`. Changing the `format` or `ppi` options does not fix this behaviour.

**Comment by gjtorikian** [comment]
Do you have the right fonts on your system? https://github.com/gjtorikian/mathematical#fonts-and-special-notices-for-mac-os-x

**Comment by lschmelzeisen** [comment]
Yes, this fixes it. I assumed having a LaTeX distribution installed was sufficient. Sorry for wasting time.
