### ISSUE TITLE
"unknown encoding name" errors building on Debian 9

### ISSUE THREAD

**Issue by oddhack** [gjtorikian/mathematical#83]
Trying to update to 1.6.11 via 'gem update' on my Debian 9 system claims to succeed, but generates 570 "unknown encoding name" errors (attached) referring to what appear to be test cases. Is this something I should be concerned about?

[encoding.txt](https://github.com/gjtorikian/mathematical/files/1697472/encoding.txt)

**Comment by gjtorikian** [comment]
Seeing as how these are all from the test fixture files, it shouldn't affect the installation/run. 

[`application/x-tex`](https://mediatemple.net/community/products/dv/204403964/mime-types) is a standard MIME type so I am not sure why Debian is confused by it.

**Comment by oddhack** [comment]
I'm unclear where the gem is getting its MIME info - /etc/mimetypes? $HOME/.mime.types? The XDG shared MIME database, which appears to be some sort of XML thing I'm unfamiliar with? If it's using the .mime.types in my $HOME that might be the issue.
