### ISSUE TITLE
Installation failed: Couldn't find header files for ruby "ruby.h"

### ISSUE THREAD

**Issue by IanOField** [gjtorikian/mathematical#84]
Installation exited because it couldn't find ruby.h.

    ERROR:  Error installing asciidoctor-mathematical:
    ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.5.0/gems/mathematical-1.6.11/ext/mathematical
    /usr/bin/ruby2.5 -r ./siteconf20180620-5797-1shuyzq.rb extconf.rb
    mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

After installing ruby2.5-dev it worked. Maybe you could/should mention that as dependency.

I'm running Debian Testing (Buster) with 4.16.12-1 (2018-05-27) kernel.

I tried to install asciidoctor-mathematical and installed all mentioned dependencies before.

**Comment by gjtorikian** [comment]
Which version of Ruby was installed previously? Or are you asking that a `*-dev` version be explicitly mentioned? (Which makes sense, just trying to sort out what the ask is.)

**Comment by IanOField** [comment]
I never installed ruby manually it was the pre installed version or at least a version which has been installed through dependencies. I think it was 2.5.0 or 2.5.1. 

But yes, i think it would be good to mention that the header files are needed so a *-dev version must be installed.
