### ISSUE TITLE
Wrong size of underbraces

### ISSUE THREAD

**Issue by RarrugasTetra** [gjtorikian/mathematical#85]
Dear Developers,
I have a problem with underbraces in my formulas; they are too small. Here is an example:

```
require 'mathematical'

var = Mathematical.new.render('$$\Phi = \underbrace{\sum_{i} \gamma_i \left( s_i M^{model}(s_i) - s_i M^{exp}(s_i) \right)}_{\Phi_{GED}} + \alpha \cdot \underbrace{ \sum_{j} \gamma_j \left( p_j^{model} - p_j^{QC} \right)}_{\Phi_{QC}} \rightarrow min$$')

File.open("test.svg", 'w'){|f| f.puts var[:data]}
```
You can run it and check the test.svg or you can see it [here](http://unexprog.org/test/test.html)

How to fix this?

Thank you.

**Comment by RarrugasTetra** [comment]
Is there any chance to fix the problem?

**Comment by 4e554c4c** [comment]
closing in favor of higher-quality issues #111 111
