### ISSUE TITLE
bundler version obsolete

### ISSUE THREAD

**Issue by opoudjis** [gjtorikian/mathematical#87]
The gemspec of this gem requires ~> bundler 1.2; bundler 1.2 does not appear to run at all with Ruby 2.5 (the `require rubygems/format` statement does not work). Strongly suggest you update dependency to latest bundler 2.0.

**Comment by opoudjis** [comment]
Some of the other gem versions used are somewhat old in the tooth now too, such as Nokogiri 1.7.

**Comment by gjtorikian** [comment]
Thanks for the report. I agree specifying Bundler is unnecessary and limiting now that 2.x is out.

WRT nokogiri and others, these are all dev requirements, used for running tests, and as such, I don't particularly need them to be up-to-date.
