### ISSUE TITLE
LaTeX package support

### ISSUE THREAD

**Issue by GarkGarcia** [gjtorikian/mathematical#96]
I'd like to know which LaTeX packages are supported. Is there a limitation on them? Or is every existing package supported?

This information should probably be included in the documentation (I wasn't able to find it).

**Comment by GarkGarcia** [comment]
If you guys need any context, you can find it on https://github.com/asciidoctor/asciimath/pull/17#issuecomment-621472983.

**Comment by gjtorikian** [comment]
It is in the docs: https://github.com/gjtorikian/mathematical#supported-commands-and-symbols

More specifically, it's the AMS-TeX package.

**Comment by GarkGarcia** [comment]
Thanks!
