### ISSUE TITLE
Can you use colors?

### ISSUE THREAD

**Issue by in3rsha** [gjtorikian/mathematical#97]
Hello there, thanks for the excellent gem.

This is a question rather than an issue: Is it possible to set the color of math symbols when using this gem? For example, this works perfectly well:

```
string_with_math = "$$x^8 + x^4 + x^3 + x + 1$$"
```

But I'm looking to do something like this:

```
string_with_math = "$$x^8 + {\color{red}x^4} + x^3 + x + 1$$"
```

Is this possible?

**Comment by gjtorikian** [comment]
Yes! See this doc for a list of everything supported: https://github.com/gjtorikian/mtex2MML/blob/master/SUPPORTED.md#colors

**Comment by in3rsha** [comment]
Ah yes, thank you. I was using double quotes `"` and it was treating the backslash as an escape character. Using single quotes `'` for the string did the trick.

Sorry for the basic question, but thanks for the help!
